Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.box_check_update = false
    config.vm.hostname = "ubungui"
    config.vm.network "private_network", ip: "192.168.56.15"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = 8192
        vb.cpus = 4
        vb.name = "Ubuntu20"
    end
    # Update repositories
    config.vm.provision :shell, inline: "sudo apt update -y"
    # Upgrade installed packages
    config.vm.provision :shell, inline: "sudo apt upgrade -y"
    # Add desktop environment
    config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends ubuntu-desktop"
    config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11"
    # Restart
    config.vm.provision :shell, inline: "sudo shutdown -r now"
end