Vagrant.configure("2") do |config|
    config.vm.box = "generic/rocky8"
    config.vm.box_check_update = false
    config.vm.hostname = "mordor"
    config.vm.network "private_network", ip: "192.168.56.16"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 8192
        vb.cpus = 2
        vb.name = "Rocky8"
    end
end