- name: Install MariaDB
  package:
    name:
      - mariadb-server
      - mariadb
      - python3-PyMySQL
    state: latest

- name: Enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: true

- name: Mysql_Root_Password
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    check_implicit_admin: true
    password: "{{ mysql_root_password }}"

- name: create a new database  
  community.mysql.mysql_db:
    name: "{{ wordpress_db }}"
    state: present 
    login_user: root 
    login_password: "{{ mysql_root_password }}"  

- name: Create user with password, all database privileges and 'WITH GRANT OPTION' in wordpress database
  community.mysql.mysql_user:
    state: present
    name: "{{ wordpress_db_user_admin }}"
    password: "{{ wordpress_db_user_passwd }}"
    priv:
      'wordpress.*': 'ALL,GRANT'
    login_user: root 
    login_password: "{{ mysql_root_password }}"